#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm install --frozen-lockfile

echo ""
echo "==================================="
echo "If you do not see any errors above, the installation process should have succeeded"
echo "==================================="
echo ""
